institution_names_list = ['association audoise sociale et medicale',
 'centre ambulatoire kleber',
 'centre antoine lacassagne centre lutte contre cancer',
 'centre cardiologie axium rambot',
 'centre cardiologie medico chirurgicale arnault tzanck',
 'centre cardiologie pays basque',
 'centre cardiologique d evecquemont',
 'centre cardiologique nord',
 'centre chirugie ophtamologique',
 'centre chirurgical emile galle',
 'centre chirurgical marie lannelongue',
 'centre clinical',
 'centre eugene marquis centre lutte contre cancer',
 'centre francois baclesse centre lutte contre cancer',
 'centre georges francois leclerc centre lutte contre cancer',
 'centre henri becquerel centre lutte contre cancer',
 'centre hospitalier',
 'centre hospitalier agen nerac',
 'centre hospitalier ardeche nord',
 'centre hospitalier basse terre',
 'centre hospitalier bastia',
 'centre hospitalier bethune beuvry',
 'centre hospitalier bigorre',
 'centre hospitalier bon sauveur',
 'centre hospitalier bretagne atlantique',
 'centre hospitalier cote basque',
 'centre hospitalier creil',
 'centre hospitalier crest',
 'centre hospitalier d angouleme',
 'centre hospitalier d hazebrouck',
 'centre hospitalier departemental georges daumezon',
 'centre hospitalier departemental vendee',
 'centre hospitalier drome vivarais',
 'centre hospitalier dubois brive',
 'centre hospitalier dunkerque',
 'centre hospitalier emile durkheim',
 'centre hospitalier erdre et loire',
 'centre hospitalier esquirol',
 'centre hospitalier eure seine',
 'centre hospitalier francois quesnay mantes jolie',
 'centre hospitalier george sand epsic cher',
 'centre hospitalier gerard marchant',
 'centre hospitalier gier',
 'centre hospitalier grasse',
 'centre hospitalier guillaume regnier rennes',
 'centre hospitalier henri laborit',
 'centre hospitalier intercommunal',
 'centre hospitalier intercommunal aix pertuis',
 'centre hospitalier intercommunal elbeuf louviers val reuil',
 'centre hospitalier intercommunal haute comte',
 'centre hospitalier intercommunal poissy st germain',
 'centre hospitalier intercommunal raincy montfermeil',
 'centre hospitalier intercommunal toulon seyne mer',
 'centre hospitalier jacques coeur bourges',
 'centre hospitalier lamentin',
 'centre hospitalier lisieux',
 'centre hospitalier lyon sud',
 'centre hospitalier mans',
 'centre hospitalier maurice despinoy',
 'centre hospitalier memorial france etats unis saint lo',
 'centre hospitalier metropole savoie',
 'centre hospitalier murets',
 'centre hospitalier national d ophtalmologie quinze vingts',
 'centre hospitalier perigueux',
 'centre hospitalier ploermel',
 'centre hospitalier prive europe',
 'centre hospitalier prive montgarde',
 'centre hospitalier prive sainte marie',
 'centre hospitalier public cotentin',
 'centre hospitalier pyrenees',
 'centre hospitalier quatre villes',
 'centre hospitalier rambouillet',
 'centre hospitalier region d annecy',
 'centre hospitalier regional d orleans source',
 'centre hospitalier regional universitaire',
 'centre hospitalier regional universitaire besancon site jean minjoz',
 'centre hospitalier rene dubos pontoise',
 'centre hospitalier roanne',
 'centre hospitalier rodez',
 'centre hospitalier rouvray',
 'centre hospitalier saint brieuc',
 'centre hospitalier saint joseph saint luc',
 'centre hospitalier saint quentin',
 'centre hospitalier specialise cadillac',
 'centre hospitalier specialise charles perrens',
 'centre hospitalier specialise chartreuse',
 'centre hospitalier specialise edouard toulouse',
 'centre hospitalier specialise henri guerin',
 'centre hospitalier specialise leon jean gregory',
 'centre hospitalier specialise mas careiron',
 'centre hospitalier specialise montfavet',
 'centre hospitalier specialise montperrin',
 'centre hospitalier specialise sainte marie',
 'centre hospitalier specialise sevrey',
 'centre hospitalier sud francilien',
 'centre hospitalier troyes',
 'centre hospitalier universitaire',
 'centre hospitalier universitaire amiens nord',
 'centre hospitalier universitaire bordeaux hopital haut leveque',
 'centre hospitalier universitaire bordeaux hopital pellegrin',
 'centre hospitalier universitaire bordeaux hopital saint andre',
 'centre hospitalier universitaire clermont ferrand gabriel montpied',
 'centre hospitalier universitaire d amiens hopital sud',
 'centre hospitalier universitaire dijon hopital bocage',
 'centre hospitalier universitaire guadeloupe pointe pitre',
 'centre hospitalier universitaire hopital arnaud villeneuve',
 'centre hospitalier universitaire hopital gui chauliac',
 'centre hospitalier universitaire hopital lapeyronie',
 'centre hospitalier universitaire hopital st eloi',
 'centre hospitalier universitaire hopital sud',
 'centre hospitalier universitaire martinique site mere enfant',
 'centre hospitalier universitaire martinique site p zobda quitman',
 'centre hospitalier universitaire nancy hopital central',
 'centre hospitalier universitaire nancy hopitaux brabois',
 'centre hospitalier universitaire nancy maternite',
 'centre hospitalier universitaire nantes hopital guillaume et rene laennec',
 'centre hospitalier universitaire nantes hopital mere enfant',
 'centre hospitalier universitaire nantes site hotel dieu hopital mere et enfant',
 'centre hospitalier universitaire nice site hopital archet',
 'centre hospitalier universitaire nice site hopital pasteur',
 'centre hospitalier universitaire nimes',
 'centre hospitalier universitaire poitiers site miletrie',
 'centre hospitalier universitaire reims american memorial hospital',
 'centre hospitalier universitaire reims hopital maison blanche',
 'centre hospitalier universitaire reims hopital robert debre',
 'centre hospitalier universitaire rennes site pontchaillou',
 'centre hospitalier universitaire reunion',
 'centre hospitalier universitaire reunion felix guyon',
 'centre hospitalier universitaire reunion sud reunion',
 'centre hospitalier universitaire saint etienne hopital nord',
 'centre hospitalier universitaire toulouse hopital larrey',
 'centre hospitalier universitaire toulouse hopital purpan',
 'centre hospitalier universitaire toulouse hopital purpan hopital meres enfants',
 'centre hospitalier universitaire toulouse hopital rangueil',
 'centre hospitalier universitaire toulouse hopitaux mere enfants',
 'centre hospitalier universitaire tours hopital bretonneau',
 'centre hospitalier universitaire tours hopital clocheville',
 'centre hospitalier universitaire tours hopital trousseau',
 'centre hospitalier valence',
 'centre hospitalier valenciennes',
 'centre hospitalier vauclaire',
 'centre hospitalier versailles',
 'centre hospitalier vichy',
 'centre hospitalier victor dupouy',
 'centre hospitalier villefranche rouergue',
 'centre hospitalier vinatier',
 'centre hospitalier william morey chalon saone',
 'centre jean perrin centre lutte contre cancer',
 'centre leon berard centre lutte contre cancer',
 'centre main',
 'centre medico chirurgical et obstetrical d evry',
 'centre medico chirurgical et obstetrique cote d opale',
 'centre medico chirurgical floreal',
 'centre medico chirurgical mans',
 'centre orthopedique medico chirurgical dracy fort',
 'centre oscar lambret centre lutte contre cancer',
 'centre psychotherapique ain',
 'centre psychotherapique nancy',
 'centre rene gauducheau centre lutte contre cancer',
 'chiva',
 'chu hopital purpan hfe',
 'clcc francois baclesse',
 'clcc rene huguenin institut curie',
 'clinique aguilera',
 'clinique alma',
 'clinique ambroise pare',
 'clinique ambulatoire domont',
 'clinique anjou',
 'clinique anne d artois',
 'clinique arago',
 'clinique atlantique',
 'clinique axium',
 'clinique beau soleil',
 'clinique belharra',
 'clinique belledonne',
 'clinique bizet',
 'clinique bon secours',
 'clinique bouchard',
 'clinique breteche',
 'clinique cambresis',
 'clinique cedre',
 'clinique cedres',
 'clinique chantecler',
 'clinique charcot',
 'clinique claude bernard',
 'clinique clementville',
 'clinique conti',
 'clinique convert',
 'clinique croise laroche',
 'clinique croix sud',
 'clinique d argonay',
 'clinique d occitanie',
 'clinique delay',
 'clinique diaconat',
 'clinique diaconat fonderie',
 'clinique drouot remusat',
 'clinique durieux',
 'clinique eaux claires',
 'clinique esperance',
 'clinique esquirol saint hilaire',
 'clinique essonne',
 'clinique estree',
 'clinique europe',
 'clinique fief grimoire',
 'clinique fontaines',
 'clinique fontvert',
 'clinique generale',
 'clinique grand large',
 'clinique honore cave',
 'clinique internationale parc monceau',
 'clinique jean bon',
 'clinique jean causse',
 'clinique jouvenet',
 'clinique juge',
 'clinique kennedy',
 'clinique lille sud',
 'clinique louis pasteur',
 'clinique marcel sembat',
 'clinique mathilde',
 'clinique maussins nollet',
 'clinique medicale et cardiologique d aressy',
 'clinique medipole garonne',
 'clinique millenaire',
 'clinique misericorde',
 'clinique monticelli velodrome',
 'clinique muette',
 'clinique mutualiste',
 'clinique mutualiste benigne joly',
 'clinique mutualiste bonneveine',
 'clinique mutualiste bretagne occidentale',
 'clinique mutualiste catalane',
 'clinique mutualiste estuaire',
 'clinique mutualiste jules verne',
 'clinique mutualiste pessac',
 'clinique mutualiste porte orient',
 'clinique mutualiste sagesse',
 'clinique ophtalmologique thiers',
 'clinique orangerie',
 'clinique orchidees',
 'clinique ormeaux',
 'clinique parc',
 'clinique parc lyon',
 'clinique paris bercy',
 'clinique paris lilas',
 'clinique part dieu',
 'clinique pasteur',
 'clinique plaine',
 'clinique pont chaume',
 'clinique pre',
 'clinique renaison',
 'clinique rhena',
 'clinique rhone durance',
 'clinique rive gauche',
 'clinique saint ame',
 'clinique saint andre',
 'clinique saint antoine',
 'clinique saint augustin',
 'clinique saint charles',
 'clinique saint francois',
 'clinique saint george',
 'clinique saint hilaire',
 'clinique saint jean dieu',
 'clinique saint jean sud france',
 'clinique saint joseph',
 'clinique saint leonard',
 'clinique saint michel',
 'clinique saint nabor',
 'clinique saint paul',
 'clinique saint pierre',
 'clinique saint vincent',
 'clinique saint vincent paul',
 'clinique sainte anne',
 'clinique sainte clotilde',
 'clinique sauvegarde',
 'clinique sport',
 'clinique tertre rouge',
 'clinique tivoli',
 'clinique toulouse lautrec',
 'clinique trenel',
 'clinique trocadero',
 'clinique turin',
 'clinique union',
 'clinique urologique nantes atlantis',
 'clinique val d or',
 'clinique val d ouest vendome',
 'clinique victor hugo',
 'clinique victor pauchet',
 'clinique villeneuve d ascq',
 'clinique vitrolles',
 'clinique yvette',
 'cmco',
 'ctre hosp saintonge saintes',
 'epsm agglomeration lilloise',
 'epsm finistere sud',
 'epsm lille metropole',
 'etablissement public sante alsace nord',
 'etablissement public sante barthelemy durand',
 'etablissement public sante mentale morbihan',
 'etablissement public sante mentale rouffach',
 'etablissement public specialise ville evrard',
 'etabt public sante mentale marne',
 'euromed cardio',
 'fondation rothschild',
 'gcs clinique ter',
 'gcs territorial ardenne nord site centre hospitalier charleville',
 'gh carnelle portes oise',
 'ghicl clinique sainte marie',
 'ghicl hopital saint philibert',
 'ghu paris psychiatrie et neurosciences',
 'grand hopital est francilien',
 'grand hopital est francilien site jossigny',
 'grand hopital est francilien site meaux',
 'groupe hospitalier bretagne sud',
 'groupe hospitalier centre alsace hopital albert schweitzer',
 'groupe hospitalier diaconesses croix saint simon',
 'groupe hospitalier havre',
 'groupe hospitalier mutualiste',
 'groupe hospitalier nord essonne',
 'groupe hospitalier paul guiraud',
 'groupe hospitalier prive ambroise pare hartmann',
 'groupe hospitalier region mulhouse et sud alsace',
 'groupe hospitalier rochelle re aunis',
 'groupe hospitalier saint joseph',
 'groupe hospitalier saint vincent',
 'groupe hospitalier seclin carvin',
 'groupement hospitalier eaubonne montmorency',
 'grpe hospitalier sud ile france',
 'gustave roussy centre lutte contre cancer',
 'hia legouest',
 'hopital ambroise pare',
 'hopital antoine beclere',
 'hopital avicenne',
 'hopital beaujon',
 'hopital bel air',
 'hopital belle isle',
 'hopital bicetre',
 'hopital bichat',
 'hopital cardiologique louis pradel',
 'hopital cavale blanche',
 'hopital charles nicolle',
 'hopital civil',
 'hopital claude huriez',
 'hopital clinique claude bernard',
 'hopital cochin',
 'hopital conception',
 'hopital cote nacre',
 'hopital croix rousse',
 'hopital croix rousse hcl centre hospitalier villefranche saone',
 'hopital croix saint simon',
 'hopital d adultes timone',
 'hopital d enfants armand trousseau',
 'hopital d estaing',
 'hopital d instruction armees begin',
 'hopital d instruction armees desgenettes',
 'hopital d instruction armees laveran',
 'hopital d instruction armees percy',
 'hopital d instruction armees robert picque',
 'hopital d instruction armees sainte anne',
 'hopital diaconesses',
 'hopital dupuytren',
 'hopital edouard herriot',
 'hopital europeen',
 'hopital europeen georges pompidou',
 'hopital femme mere enfant',
 'hopital fernand widal',
 'hopital foch',
 'hopital fondation hotel dieu creusot',
 'hopital franco britannique kleber',
 'hopital hautepierre',
 'hopital henri mondor',
 'hopital hotel dieu',
 'hopital institut coeur poumon',
 'hopital jean verdier',
 'hopital jeanne flandre',
 'hopital joseph ducuing',
 'hopital lariboisiere',
 'hopital larrey',
 'hopital lenval',
 'hopital louis mourier',
 'hopital massues',
 'hopital mercy',
 'hopital mere et enfant',
 'hopital morvan',
 'hopital necker enfants malades',
 'hopital neurologique pierre wertheimer',
 'hopital nord',
 'hopital nord franche comte',
 'hopital nord ouest',
 'hopital paris saint joseph',
 'hopital paul brousse',
 'hopital pitie salpetriere',
 'hopital prive armand brillard',
 'hopital prive arras bonnettes',
 'hopital prive baie',
 'hopital prive beauregard',
 'hopital prive bois',
 'hopital prive bois bernard',
 'hopital prive cannes oxford',
 'hopital prive casamance',
 'hopital prive chataigneraie',
 'hopital prive clairval',
 'hopital prive claude galien',
 'hopital prive confluent',
 'hopital prive cotes d armor',
 'hopital prive d antony',
 'hopital prive dijon bourgogne',
 'hopital prive drome ardeche',
 'hopital prive est lyonnais',
 'hopital prive estuaire',
 'hopital prive franciscaines',
 'hopital prive geoffroy saint hilaire',
 'hopital prive jacques cartier',
 'hopital prive jean mermoz',
 'hopital prive loire',
 'hopital prive louviere',
 'hopital prive marne chantereine',
 'hopital prive marne vallee',
 'hopital prive miotte',
 'hopital prive montagne lambert',
 'hopital prive nancy lorraine',
 'hopital prive natecia',
 'hopital prive nord parisien',
 'hopital prive oceane',
 'hopital prive ouest parisien',
 'hopital prive paris essonne charmilles',
 'hopital prive parly ii',
 'hopital prive paul d egine',
 'hopital prive pays savoie',
 'hopital prive peupliers',
 'hopital prive provence',
 'hopital prive saint francois',
 'hopital prive saint gregoire',
 'hopital prive saint martin',
 'hopital prive sainte marie',
 'hopital prive seine saint denis',
 'hopital prive sevigne',
 'hopital prive toulon hyeres saint jean',
 'hopital prive vert coteau',
 'hopital prive vert galant',
 'hopital prive villeneuve d ascq',
 'hopital raymond poincare',
 'hopital renee sabran',
 'hopital robert debre',
 'hopital robert schuman',
 'hopital roger salengro',
 'hopital saint antoine',
 'hopital saint camille',
 'hopital saint joseph',
 'hopital saint louis',
 'hopital saint vincent paul ghicl',
 'hopital sud',
 'hopital tenon',
 'hopital timone enfants',
 'hopitaux civils',
 'hopitaux lannemezan',
 'hopitaux nord ardennes',
 'hopitaux prives metz',
 'hopitaux saint maurice',
 'hopitaux sud',
 'hopitaux universitaires strasbourg',
 'hotel dieu',
 'hu paris ouest hopital corentin celton',
 'infirmerie protestante lyon',
 'institut arnault tzanck',
 'institut arthur vernes',
 'institut bergonie centre lutte contre cancer',
 'institut calot',
 'institut cancerologie lorraine alexis vautrin',
 'institut cancerologie ouest site paul papin',
 'institut cancerologie strasbourg europe icans',
 'institut claudius regaud centre lutte contre cancer',
 'institut curie',
 'institut curie centre lutte contre cancer',
 'institut d hematologie et oncologie pediatrique',
 'institut jean godinot centre lutte contre cancer',
 'institut mutualiste montsouris',
 'institut ophtalmique',
 'institut ophtalmologique picardie',
 'institut paoli calmettes centre lutte contre cancer',
 'institut regional cancer montpellier',
 'institut universitaire cancer oncopole',
 'institut universitaire face et cou',
 'maison sante bagatelle',
 'medipole lyon villeurbanne',
 'medipole savoie',
 'nouvel hopital navarre',
 'nouvelle clinique bel air',
 'nouvelle clinique bordeaux tondu',
 'nouvelle clinique ciotat',
 'nouvelles cliniques tours',
 'pole sante leonard vinci',
 'pole sante oreliance',
 'pole sante republique',
 'pole sante villeneuvois',
 'polyclinique beaujolais',
 'polyclinique blois',
 'polyclinique bordeaux nord aquitaine',
 'polyclinique bordeaux rive droite',
 'polyclinique cote basque sud',
 'polyclinique courlancy',
 'polyclinique d henin beaumont',
 'polyclinique fleurs',
 'polyclinique francheville',
 'polyclinique grand sud',
 'polyclinique jean villar',
 'polyclinique keraudren',
 'polyclinique kerio',
 'polyclinique ligne bleue',
 'polyclinique limoges',
 'polyclinique limoges site chenieux',
 'polyclinique limoges site emailleurs colombier',
 'polyclinique lyon nord',
 'polyclinique maine',
 'polyclinique majorelle',
 'polyclinique medipole saint roch',
 'polyclinique mediterranee',
 'polyclinique ormeau site centre',
 'polyclinique ormeau site pyrenees',
 'polyclinique parc',
 'polyclinique parc drevon',
 'polyclinique pau pyrenees site navarre',
 'polyclinique pergola',
 'polyclinique picardie',
 'polyclinique poitiers',
 'polyclinique region mantaise',
 'polyclinique reims bezannes',
 'polyclinique saint come',
 'polyclinique saint jean',
 'polyclinique saint jean ermitage',
 'polyclinique saint laurent',
 'polyclinique saint privat',
 'polyclinique saint roch',
 'polyclinique santa maria',
 'polyclinique urbain v',
 'polyclinique vauban',
 'sante atlantique']