institution_names_type_dict = {'centre cardiologie medico chirurgicale arnault tzanck': 'Public',
 'hopital nord': 'Public',
 'hopital d adultes timone': 'Public',
 'hopital saint joseph': 'Public',
 'centre hospitalier': 'Public',
 'centre hospitalier universitaire': 'Public',
 'centre hospitalier bretagne atlantique': 'Public',
 'centre hospitalier saint joseph saint luc': 'Public',
 'groupe hospitalier saint joseph': 'Public',
 'hopital pitie salpetriere': 'Public',
 'institut mutualiste montsouris': 'Public',
 'hopital europeen georges pompidou': 'Public',
 'centre hospitalier departemental vendee': 'Public',
 'centre hospitalier intercommunal raincy montfermeil': 'Public',
 'hopital henri mondor': 'Public',
 'hopital croix rousse': 'Public',
 'hopital cardiologique louis pradel': 'Public',
 'clinique saint george': 'Privé',
 'hopital prive clairval': 'Privé',
 'hopital prive saint martin': 'Privé',
 'clinique saint vincent': 'Privé',
 'hopital prive franciscaines': 'Privé',
 'clinique pasteur': 'Privé',
 'clinique saint augustin': 'Privé',
 'clinique millenaire': 'Privé',
 'clinique parc': 'Privé',
 'nouvelles cliniques tours': 'Privé',
 'hopital prive confluent': 'Privé',
 'pole sante oreliance': 'Privé',
 'clinique esquirol saint hilaire': 'Privé',
 'clinique saint joseph': 'Privé',
 'clinique louis pasteur': 'Privé',
 'hopital clinique claude bernard': 'Privé',
 'polyclinique vauban': 'Privé',
 'hopital prive bois': 'Privé',
 'hopital prive bois bernard': 'Privé',
 'pole sante republique': 'Privé',
 'clinique medicale et cardiologique d aressy': 'Privé',
 'clinique saint pierre': 'Privé',
 'polyclinique lyon nord': 'Privé',
 'clinique sauvegarde': 'Privé',
 'infirmerie protestante lyon': 'Privé',
 'clinique saint hilaire': 'Privé',
 'clinique fontaines': 'Privé',
 'hopital prive parly ii': 'Privé',
 'polyclinique fleurs': 'Privé',
 'clinique rhone durance': 'Privé',
 'hopital prive jacques cartier': 'Privé',
 'hopital prive claude galien': 'Privé',
 'groupe hospitalier prive ambroise pare hartmann': 'Privé',
 'centre cardiologique nord': 'Privé',
 'centre hospitalier region d annecy': 'Public',
 'ghicl hopital saint philibert': 'Privé',
 'hopital civil': 'Public',
 'centre hospitalier universitaire toulouse hopital rangueil': 'Public',
 'centre hospitalier universitaire bordeaux hopital haut leveque': 'Public',
 'centre hospitalier universitaire reunion sud reunion': 'Public',
 'hopital cote nacre': 'Public',
 'centre hospitalier universitaire dijon hopital bocage': 'Public',
 'centre hospitalier regional universitaire besancon site jean minjoz': 'Public',
 'hopital cavale blanche': 'Public',
 'centre hospitalier universitaire hopital arnaud villeneuve': 'Public',
 'centre hospitalier universitaire rennes site pontchaillou': 'Public',
 'centre hospitalier universitaire tours hopital trousseau': 'Public',
 'centre hospitalier universitaire saint etienne hopital nord': 'Public',
 'centre hospitalier universitaire nantes hopital guillaume et rene laennec': 'Public',
 'hopital larrey': 'Public',
 'centre hospitalier universitaire reims hopital robert debre': 'Public',
 'centre hospitalier universitaire nancy hopitaux brabois': 'Public',
 'hopital mercy': 'Public',
 'hopital institut coeur poumon': 'Public',
 'centre hospitalier universitaire clermont ferrand gabriel montpied': 'Public',
 'hopital charles nicolle': 'Public',
 'hopital dupuytren': 'Public',
 'centre hospitalier universitaire nice site hopital pasteur': 'Public',
 'centre hospitalier universitaire poitiers site miletrie': 'Public',
 'centre hospitalier universitaire d amiens hopital sud': 'Public',
 'groupe hospitalier rochelle re aunis': 'Public',
 'centre hospitalier intercommunal toulon seyne mer': 'Public',
 'centre cardiologie pays basque': 'Privé',
 'clinique rhena': 'Privé',
 'grand hopital est francilien': 'Public',
 'polyclinique reims bezannes': 'Privé',
 'polyclinique saint laurent': 'Privé',
 'hopital prive nancy lorraine': 'Privé',
 'medipole lyon villeurbanne': 'Privé',
 'maison sante bagatelle': 'Public',
 'clinique mutualiste': 'Privé',
 'clinique mutualiste jules verne': 'Privé',
 'clinique mutualiste porte orient': 'Public',
 'groupe hospitalier saint vincent': 'Public',
 'hopitaux civils': 'Public',
 'groupe hospitalier centre alsace hopital albert schweitzer': 'Public',
 'groupe hospitalier mutualiste': 'Public',
 'clinique atlantique': 'Privé',
 'clinique grand large': 'Privé',
 'clinique cedres': 'Privé',
 'hopital prive saint gregoire': 'Privé',
 'hopital prive sevigne': 'Privé',
 'sante atlantique': 'Privé',
 'clinique cambresis': 'Privé',
 'hopital prive chataigneraie': 'Privé',
 'polyclinique pau pyrenees site navarre': 'Privé',
 'clinique diaconat': 'Privé',
 'medipole savoie': 'Privé',
 'clinique generale': 'Privé',
 'hopital prive estuaire': 'Privé',
 'clinique europe': 'Privé',
 'centre hospitalier prive europe': 'Privé',
 'polyclinique picardie': 'Privé',
 'clinique fontvert': 'Privé',
 'clinique claude bernard': 'Privé',
 'clinique misericorde': 'Privé',
 'clinique mutualiste estuaire': 'Public',
 'centre hospitalier ploermel': 'Public',
 'hopital robert schuman': 'Privé',
 'clinique rive gauche': 'Privé',
 'hopital prive cotes d armor': 'Privé',
 'clinique villeneuve d ascq': 'Privé',
 'centre hospitalier saint quentin': 'Public',
 'centre hospitalier vichy': 'Public',
 'centre hospitalier ardeche nord': 'Public',
 'chiva': 'Public',
 'centre hospitalier rodez': 'Public',
 'centre hospitalier valence': 'Public',
 'hotel dieu': 'Privé',
 'centre hospitalier agen nerac': 'Public',
 'centre hospitalier william morey chalon saone': 'Public',
 'gcs clinique ter': 'Public',
 'clinique mutualiste pessac': 'Public',
 'clinique beau soleil': 'Public',
 'clinique mutualiste sagesse': 'Public',
 'centre hospitalier bigorre': 'Public',
 'hopital edouard herriot': 'Public',
 'centre hospitalier metropole savoie': 'Public',
 'hopital cochin': 'Public',
 'centre hospitalier national d ophtalmologie quinze vingts': 'Public',
 'fondation rothschild': 'Public',
 'hopital nord franche comte': 'Public',
 'hopital foch': 'Public',
 'hopital ambroise pare': 'Public',
 'centre hospitalier intercommunal': 'Public',
 'groupement hospitalier eaubonne montmorency': 'Public',
 'hopital prive cannes oxford': 'Privé',
 'polyclinique saint jean': 'Privé',
 'clinique monticelli velodrome': 'Privé',
 'clinique axium': 'Privé',
 'centre clinical': 'Privé',
 'clinique union': 'Privé',
 'nouvelle clinique bel air': 'Privé',
 'clinique ophtalmologique thiers': 'Privé',
 'clinique belledonne': 'Privé',
 'clinique anjou': 'Privé',
 'hopital prive baie': 'Privé',
 'polyclinique courlancy': 'Privé',
 'clinique saint andre': 'Privé',
 'hopital prive oceane': 'Privé',
 'institut ophtalmique': 'Privé',
 'clinique ambroise pare': 'Privé',
 'hopital prive louviere': 'Privé',
 'clinique delay': 'Privé',
 'clinique mutualiste catalane': 'Privé',
 'polyclinique medipole saint roch': 'Privé',
 'clinique diaconat fonderie': 'Privé',
 'hopital prive sainte marie': 'Privé',
 'centre medico chirurgical mans': 'Privé',
 'hopital prive geoffroy saint hilaire': 'Privé',
 'clinique saint jean dieu': 'Privé',
 'clinique jouvenet': 'Privé',
 'clinique muette': 'Privé',
 'clinique mathilde': 'Privé',
 'clinique honore cave': 'Privé',
 'polyclinique limoges site chenieux': 'Privé',
 'hopital prive d antony': 'Privé',
 'centre hospitalier prive sainte marie': 'Privé',
 'hopital d instruction armees desgenettes': 'Public',
 'clinique saint michel': 'Privé',
 'institut ophtalmologique picardie': 'Privé',
 'centre hospitalier universitaire tours hopital bretonneau': 'Public',
 'centre hospitalier universitaire toulouse hopital purpan': 'Public',
 'centre hospitalier universitaire hopital gui chauliac': 'Public',
 'groupe hospitalier region mulhouse et sud alsace': 'Public',
 'centre chirugie ophtamologique': 'Public',
 'gcs territorial ardenne nord site centre hospitalier charleville': 'Public',
 'pole sante villeneuvois': 'Privé',
 'hopital prive dijon bourgogne': 'Privé',
 'centre hospitalier villefranche rouergue': 'Public',
 'centre hospitalier jacques coeur bourges': 'Public',
 'polyclinique saint roch': 'Privé',
 'centre hospitalier d hazebrouck': 'Public',
 'centre hospitalier francois quesnay mantes jolie': 'Public',
 'clinique croix sud': 'Privé',
 'clinique mutualiste bretagne occidentale': 'Privé',
 'hopital bicetre': 'Public',
 'clinique juge': 'Privé',
 'hopital claude huriez': 'Public',
 'centre hospitalier universitaire bordeaux hopital pellegrin': 'Public',
 'centre hospitalier universitaire nantes site hotel dieu hopital mere et enfant': 'Public',
 'centre ambulatoire kleber': 'Privé',
 'centre chirurgical emile galle': 'Public',
 'centre hospitalier lyon sud': 'Public',
 'hopital renee sabran': 'Public',
 'centre hospitalier mans': 'Public',
 'polyclinique parc': 'Privé',
 'clinique medipole garonne': 'Privé',
 'clinique sport': 'Privé',
 'clinique saint leonard': 'Privé',
 'clinique lille sud': 'Privé',
 'clinique orangerie': 'Privé',
 'clinique saint charles': 'Privé',
 'clinique pre': 'Privé',
 'clinique victor hugo': 'Privé',
 'clinique cedre': 'Privé',
 'hopital europeen': 'Public',
 'clinique sainte anne': 'Privé',
 'hopital roger salengro': 'Public',
 'centre hospitalier universitaire hopital lapeyronie': 'Public',
 'clinique saint antoine': 'Privé',
 'nouvelle clinique ciotat': 'Privé',
 'centre hospitalier crest': 'Public',
 'centre hospitalier gier': 'Public',
 'centre hospitalier valenciennes': 'Public',
 'clinique ambulatoire domont': 'Privé',
 'hopital croix saint simon': 'Privé',
 'clinique saint jean sud france': 'Privé',
 'hopital tenon': 'Public',
 'hopital prive saint francois': 'Privé',
 'clinique esperance': 'Privé',
 'hopital prive beauregard': 'Privé',
 'hopital prive provence': 'Privé',
 'polyclinique grand sud': 'Privé',
 'clinique d occitanie': 'Privé',
 'polyclinique saint privat': 'Privé',
 'polyclinique blois': 'Privé',
 'polyclinique saint come': 'Privé',
 'clinique ormeaux': 'Privé',
 'clinique toulouse lautrec': 'Privé',
 'hopital prive vert galant': 'Privé',
 'clinique orchidees': 'Privé',
 'clinique sainte clotilde': 'Privé',
 'hopital nord ouest': 'Public',
 'clinique chantecler': 'Privé',
 'clinique bon secours': 'Privé',
 'centre hospitalier regional d orleans source': 'Public',
 'polyclinique pergola': 'Privé',
 'centre hospitalier grasse': 'Public',
 'centre hospitalier d angouleme': 'Public',
 'groupe hospitalier seclin carvin': 'Public',
 'polyclinique saint jean ermitage': 'Privé',
 'hopitaux nord ardennes': 'Public',
 'hopital bichat': 'Public',
 'groupe hospitalier havre': 'Public',
 'centre chirurgical marie lannelongue': 'Public',
 'hopital avicenne': 'Public',
 'centre hospitalier bethune beuvry': 'Public',
 'hopital prive vert coteau': 'Privé',
 'polyclinique bordeaux rive droite': 'Privé',
 'polyclinique bordeaux nord aquitaine': 'Privé',
 'pole sante leonard vinci': 'Privé',
 'hopital prive loire': 'Privé',
 'centre medico chirurgical et obstetrique cote d opale': 'Privé',
 'polyclinique ormeau site centre': 'Privé',
 'hopital prive jean mermoz': 'Privé',
 'hopital prive ouest parisien': 'Privé',
 'clinique pont chaume': 'Privé',
 'clinique val d or': 'Privé',
 'institut arnault tzanck': 'Privé',
 'clinique eaux claires': 'Privé',
 'centre hospitalier universitaire toulouse hopital larrey': 'Public',
 'centre hospitalier universitaire reims hopital maison blanche': 'Public',
 'clinique belharra': 'Privé',
 'centre hospitalier universitaire martinique site p zobda quitman': 'Public',
 'hopital prive seine saint denis': 'Privé',
 'hopital prive marne chantereine': 'Privé',
 'centre hospitalier eure seine': 'Public',
 'polyclinique d henin beaumont': 'Public',
 'hopital saint antoine': 'Public',
 'polyclinique keraudren': 'Privé',
 'clinique tivoli': 'Privé',
 'clinique val d ouest vendome': 'Privé',
 'hopital prive toulon hyeres saint jean': 'Privé',
 'hopital saint vincent paul ghicl': 'Public',
 'centre hospitalier intercommunal poissy st germain': 'Public',
 'institut paoli calmettes centre lutte contre cancer': 'Public',
 'clinique urologique nantes atlantis': 'Privé',
 'clinique turin': 'Privé',
 'centre hospitalier universitaire guadeloupe pointe pitre': 'Privé',
 'hopital fondation hotel dieu creusot': 'Public',
 'centre hospitalier universitaire martinique site mere enfant': 'Public',
 'ctre hosp saintonge saintes': 'Public',
 'centre hospitalier rene dubos pontoise': 'Public',
 'centre antoine lacassagne centre lutte contre cancer': 'Public',
 'centre francois baclesse centre lutte contre cancer': 'Public',
 'centre georges francois leclerc centre lutte contre cancer': 'Public',
 'institut bergonie centre lutte contre cancer': 'Public',
 'institut regional cancer montpellier': 'Public',
 'centre eugene marquis centre lutte contre cancer': 'Public',
 'centre rene gauducheau centre lutte contre cancer': 'Public',
 'institut cancerologie ouest site paul papin': 'Public',
 'institut jean godinot centre lutte contre cancer': 'Public',
 'institut cancerologie lorraine alexis vautrin': 'Public',
 'groupe hospitalier bretagne sud': 'Public',
 'centre oscar lambret centre lutte contre cancer': 'Public',
 'centre jean perrin centre lutte contre cancer': 'Public',
 'centre leon berard centre lutte contre cancer': 'Public',
 'hopital saint louis': 'Public',
 'institut curie centre lutte contre cancer': 'Public',
 'centre henri becquerel centre lutte contre cancer': 'Public',
 'gustave roussy centre lutte contre cancer': 'Public',
 'clinique clementville': 'Privé',
 'clinique charcot': 'Privé',
 'clinique bizet': 'Privé',
 'clinique victor pauchet': 'Privé',
 'polyclinique urbain v': 'Privé',
 'clinique fief grimoire': 'Privé',
 'hopital morvan': 'Public',
 'hopital mere et enfant': 'Public',
 'hopital prive drome ardeche': 'Privé',
 'clcc rene huguenin institut curie': 'Public',
 'centre hospitalier universitaire toulouse hopital purpan hopital meres enfants': 'Public',
 'institut cancerologie strasbourg europe icans': 'Public',
 'hopital conception': 'Public',
 'hopital lariboisiere': 'Public',
 'hopital hautepierre': 'Public',
 'hopitaux sud': 'Public',
 'centre hospitalier cote basque': 'Public',
 'centre hospitalier versailles': 'Public',
 'hopital d instruction armees sainte anne': 'Public',
 'clinique croise laroche': 'Privé',
 'clinique d argonay': 'Privé',
 'clinique arago': 'Privé',
 'clinique maussins nollet': 'Privé',
 'clinique paris lilas': 'Privé',
 'institut calot': 'Privé',
 'hopital sud': 'Public',
 'clinique drouot remusat': 'Privé',
 'clinique renaison': 'Privé',
 'hopital prive arras bonnettes': 'Privé',
 'centre orthopedique medico chirurgical dracy fort': 'Privé',
 'polyclinique poitiers': 'Privé',
 'polyclinique ligne bleue': 'Privé',
 'clinique aguilera': 'Privé',
 'hopital prive pays savoie': 'Privé',
 'clinique saint nabor': 'Privé',
 'hopital prive miotte': 'Privé',
 'centre hospitalier victor dupouy': 'Public',
 'nouvelle clinique bordeaux tondu': 'Privé',
 'centre hospitalier saint brieuc': 'Public',
 'polyclinique maine': 'Privé',
 'polyclinique ormeau site pyrenees': 'Privé',
 'centre hospitalier lamentin': 'Public',
 'hopital prive casamance': 'Privé',
 'centre hospitalier intercommunal elbeuf louviers val reuil': 'Public',
 'clinique mutualiste benigne joly': 'Privé',
 'hopital prive villeneuve d ascq': 'Privé',
 'centre hospitalier universitaire nice site hopital archet': 'Public',
 'centre medico chirurgical et obstetrical d evry': 'Privé',
 'centre hospitalier perigueux': 'Public',
 'hopital necker enfants malades': 'Public',
 'hopital raymond poincare': 'Public',
 'centre hospitalier universitaire toulouse hopitaux mere enfants': 'Public',
 'hopital antoine beclere': 'Public',
 'clinique bouchard': 'Privé',
 'clinique breteche': 'Privé',
 'centre hospitalier universitaire hopital st eloi': 'Public',
 'hopital prive est lyonnais': 'Privé',
 'hopital robert debre': 'Public',
 'clinique part dieu': 'Privé',
 'hopital lenval': 'Public',
 'hopital d enfants armand trousseau': 'Public',
 'clinique jean causse': 'Privé',
 'clinique saint ame': 'Privé',
 'clinique marcel sembat': 'Privé',
 'clinique durieux': 'Privé',
 'clinique paris bercy': 'Privé',
 'institut arthur vernes': 'Privé',
 'centre hospitalier universitaire tours hopital clocheville': 'Public',
 'ghicl clinique sainte marie': 'Privé',
 'centre hospitalier intercommunal aix pertuis': 'Public',
 'hopital prive montagne lambert': 'Privé',
 'hopital neurologique pierre wertheimer': 'Public',
 'centre hospitalier universitaire nancy hopital central': 'Public',
 'ghu paris psychiatrie et neurosciences': 'Public',
 'institut universitaire face et cou': 'Public',
 'hopital beaujon': 'Public',
 'hopital d estaing': 'Public',
 'centre hospitalier universitaire reunion felix guyon': 'Public',
 'clinique plaine': 'Privé',
 'clinique saint paul': 'Privé',
 'centre hospitalier dubois brive': 'Public',
 'institut claudius regaud centre lutte contre cancer': 'Public',
 'centre hospitalier regional universitaire': 'Public',
 'clinique kennedy': 'Privé',
 'centre main': 'Privé',
 'hopital prive peupliers': 'Privé',
 'centre hospitalier prive montgarde': 'Privé',
 'clinique yvette': 'Privé',
 'hopital prive paul d egine': 'Privé',
 'clinique conti': 'Privé',
 'centre medico chirurgical floreal': 'Privé',
 'hopital belle isle': 'Privé',
 'clinique saint francois': 'Privé',
 'centre hospitalier intercommunal haute comte': 'Public',
 'hopital saint camille': 'Public',
 'hopital femme mere enfant': 'Public',
 'clinique estree': 'Privé',
 'groupe hospitalier nord essonne': 'Public',
 'hopital massues': 'Privé',
 'hopital hotel dieu': 'Public',
 'centre hospitalier universitaire bordeaux hopital saint andre': 'Public',
 'hopital franco britannique kleber': 'Privé',
 'polyclinique beaujolais': 'Privé',
 'clinique trocadero': 'Privé',
 'hopital louis mourier': 'Public',
 'hopitaux saint maurice': 'Public',
 'etablissement public specialise ville evrard': 'Public',
 'centre hospitalier specialise chartreuse': 'Public',
 'centre hospitalier specialise charles perrens': 'Public',
 'etablissement public sante barthelemy durand': 'Public',
 'centre hospitalier rouvray': 'Public',
 'etablissement public sante mentale rouffach': 'Public',
 'centre hospitalier pyrenees': 'Public',
 'etablissement public sante mentale morbihan': 'Public',
 'centre psychotherapique nancy': 'Public',
 'centre psychotherapique ain': 'Public',
 'centre hospitalier vauclaire': 'Public',
 'centre hospitalier universitaire nimes': 'Public',
 'hopitaux lannemezan': 'Public',
 'centre hospitalier specialise sevrey': 'Public',
 'centre hospitalier drome vivarais': 'Public',
 'etabt public sante mentale marne': 'Public',
 'centre hospitalier henri laborit': 'Public',
 'groupe hospitalier paul guiraud': 'Public',
 'centre hospitalier specialise montperrin': 'Public',
 'centre hospitalier george sand epsic cher': 'Public',
 'nouvel hopital navarre': 'Public',
 'centre hospitalier guillaume regnier rennes': 'Public',
 'epsm lille metropole': 'Public',
 'etablissement public sante alsace nord': 'Public',
 'centre hospitalier vinatier': 'Public',
 'centre hospitalier esquirol': 'Public',
 'hopital fernand widal': 'Public',
 'hopitaux universitaires strasbourg': 'Public',
 'centre hospitalier specialise leon jean gregory': 'Public',
 'centre hospitalier gerard marchant': 'Public',
 'centre hospitalier specialise sainte marie': 'Public',
 'centre hospitalier murets': 'Public',
 'epsm agglomeration lilloise': 'Public',
 'centre hospitalier maurice despinoy': 'Public',
 'polyclinique kerio': 'Privé',
 'hopital paul brousse': 'Public',
 'polyclinique parc drevon': 'Privé',
 'groupe hospitalier diaconesses croix saint simon': 'Public',
 'hopitaux prives metz': 'Privé',
 'polyclinique limoges': 'Privé',
 'clinique parc lyon': 'Privé',
 'hopital paris saint joseph': 'Public',
 'polyclinique jean villar': 'Privé',
 'polyclinique limoges site emailleurs colombier': 'Privé',
 'hopital prive paris essonne charmilles': 'Privé',
 'clinique mutualiste bonneveine': 'Privé',
 'clinique vitrolles': 'Privé',
 'hopital prive marne vallee': 'Privé',
 'centre hospitalier roanne': 'Public',
 'centre hospitalier erdre et loire': 'Public',
 'polyclinique cote basque sud': 'Privé',
 'hopital d instruction armees percy': 'Public',
 'hopital timone enfants': 'Public',
 'hopital jeanne flandre': 'Public',
 'centre hospitalier universitaire hopital sud': 'Public',
 'centre hospitalier universitaire reims american memorial hospital': 'Public',
 'institut d hematologie et oncologie pediatrique': 'Public',
 'clinique trenel': 'Privé',
 'clinique alma': 'Privé',
 'centre hospitalier public cotentin': 'Public',
 'centre hospitalier creil': 'Public',
 'centre hospitalier universitaire nancy maternite': 'Public',
 'grand hopital est francilien site meaux': 'Public',
 'centre hospitalier dunkerque': 'Public',
 'hopital jean verdier': 'Public',
 'polyclinique majorelle': 'Privé',
 'polyclinique mediterranee': 'Privé',
 'clinique saint vincent paul': 'Privé',
 'hopital prive armand brillard': 'Privé',
 'clinique tertre rouge': 'Privé',
 'centre hospitalier rambouillet': 'Public',
 'centre hospitalier emile durkheim': 'Public',
 'hopital joseph ducuing': 'Privé',
 'centre hospitalier lisieux': 'Public',
 'centre hospitalier memorial france etats unis saint lo': 'Public',
 'hopital prive natecia': 'Privé',
 'grpe hospitalier sud ile france': 'Public',
 'centre hospitalier quatre villes': 'Public',
 'gh carnelle portes oise': 'Public',
 'cmco': 'Public',
 'hopital diaconesses': 'Privé',
 'grand hopital est francilien site jossigny': 'Public',
 'centre hospitalier sud francilien': 'Public',
 'institut universitaire cancer oncopole': 'Public',
 'clcc francois baclesse': 'Public',
 'chu hopital purpan hfe': 'Public',
 'institut curie': 'Public',
 'polyclinique region mantaise': 'Privé',
 'clinique jean bon': 'Privé',
 'clinique convert': 'Privé',
 'centre cardiologie axium rambot': 'Privé',
 'euromed cardio': 'Privé',
 'centre cardiologique d evecquemont': 'Privé',
 'hopital croix rousse hcl centre hospitalier villefranche saone': 'Public',
 'centre hospitalier universitaire amiens nord': 'Public',
 'centre hospitalier troyes': 'Public',
 'hopital bel air': 'Public',
 'clinique essonne': 'Privé',
 'hopital prive nord parisien': 'Privé',
 'clinique internationale parc monceau': 'Privé',
 'centre hospitalier basse terre': 'Public',
 'clinique anne d artois': 'Privé',
 'polyclinique santa maria': 'Privé',
 'polyclinique francheville': 'Privé',
 'centre hospitalier bastia': 'Public',
 'centre hospitalier universitaire nantes hopital mere enfant': 'Public',
 'association audoise sociale et medicale': 'Public',
 'centre hospitalier bon sauveur': 'Public',
 'centre hospitalier specialise mas careiron': 'Public',
 'centre hospitalier specialise henri guerin': 'Public',
 'hopital d instruction armees laveran': 'Public',
 'hopital d instruction armees begin': 'Public',
 'centre hospitalier universitaire reunion': 'Public',
 'centre hospitalier specialise montfavet': 'Public',
 'epsm finistere sud': 'Public',
 'hu paris ouest hopital corentin celton': 'Public',
 'hopital d instruction armees robert picque': 'Public',
 'hia legouest': 'Public',
 'centre hospitalier specialise edouard toulouse': 'Public',
 'centre hospitalier specialise cadillac': 'Public',
 'centre hospitalier departemental georges daumezon': 'Public'}