"""
Dictionaries and lists for medical specialties and their variations.
These are used for categorizing and matching user queries to relevant medical specialties."""

# Dictionary mapping main specialties to their sub-specialties or procedures
specialty_categories_dict = {
        "maternités": ["Accouchements normaux", "Accouchements à risques"],
        "cardiologie": ["Angioplastie coronaire", "Cardiologie interventionnelle", "Chirurgie cardiaque adulte", "Chirurgie cardiaque pédiatrique", "Infarctus du myocarde", "Insuffisance cardiaque", "Rythmologie"],
        "veines et artères": ["Ablation des varices", "Chirurgie des artères", "Chirurgie des carotides", "Hypertension artérielle", "Médecine vasculaire"],
        "orthopédie": ["Arthrose de la main", "Chirurgie de l'épaule", "Chirurgie de la cheville", "Chirurgie du canal carpien", "Chirurgie du dos de l'adulte", "Chirurgie du dos de l'enfant et de l’adolescent", "Chirurgie du pied", "Ligaments du genou", "Prothèse de genou", "Prothèse de hanche"],
        "ophtalmologie": ["Cataracte", "Chirurgie de la cornée", "Chirurgie de la rétine", "Glaucome", "Strabisme"],
        "gynécologie et cancers de la femme": ["Cancer de l'ovaire", "Cancer de l'utérus", "Cancer du sein", "Endométriose", "Fibrome utérin"],
        "appareil digestif": ["Appendicite", "Cancer de l'estomac ou de l'œsophage", "Cancer du côlon ou de l'intestin", "Cancer du foie", "Cancer du pancréas", "Chirurgie de l'obésité", "Chirurgie du rectum", "Hernies de l'abdomen", "Maladies inflammatoires chroniques de l'intestin (MICI)", "Proctologie"],
        "psychiatrie": ["Dépression", "Schizophrénie"],
        "urologie": ["Adénome de la prostate", "Calculs urinaires", "Cancer de la prostate", "Cancer de la vessie", "Cancer du rein", "Chirurgie des testicules de l’adulte", "Chirurgie des testicules de l’enfant et de l’adolescent"],
        "tête et cou": ["Amygdales et végétations", "Audition", "Cancer ORL", "Chirurgie dentaire et orale de l’adulte", "Chirurgie dentaire et orale de l’enfant et de l’adolescent", "Chirurgie du nez et des sinus", "Chirurgie maxillo-faciale", "Glandes salivaires"],
        "neurologie": ["Accidents vasculaires cérébraux", "Epilepsie de l’adulte", "Epilepsie de l’enfant et de l’adolescent", "Maladie de Parkinson"],
        "cancer": ["Cancer de l'estomac ou de l'œsophage", "Cancer de l'ovaire", "Cancer de l'utérus", "Cancer de la prostate", "Cancer de la thyroïde", "Cancer de la vessie", "Cancer des os de l’enfant et de l’adolescent", "Cancer du côlon ou de l'intestin", "Cancer du foie", "Cancer du pancréas", "Cancer du poumon", "Cancer du rein", "Cancer du sein", "Cancer ORL", "Cancers de la peau", "Chirurgie des cancers osseux de l'adulte", "Chirurgie des sarcomes des tissus mous", "Leucémie de l'adulte", "Leucémie de l'enfant et de l’adolescent", "Lymphome-myélome de l’adulte", "Tumeurs du cerveau de l'adulte", "Tumeurs du cerveau de l’enfant et de l’adolescent"],
        "diabète": ["Diabète de l'adulte", "Diabète de l'enfant et de l’adolescent"]
    }

category_variations = {
            "maternités": ["maternités", "maternité", "maternités", "accouchement", "accouchements", "grossesse", "enceinte", "bébé", "nouveau-né"],
            "gynécologie et cancers de la femme": ["gynécologie et cancers de la femme", "gynécologie", "gynéco", "femme", "femmes", "utérus", "ovaires", "sein", "seins", "gynécologique"],
            "ophtalmologie": ["ophtalmologie", "ophtalmologique", "yeux", "œil", "oeil", "vision", "vue", "regard", "ophtalmo"],
            "appareil digestif": ["appareil digestif", "digestif", "digestion", "intestin", "intestins", "estomac", "ventre", "abdomen", "abdominal", "gastro"],
            "tête et cou": ["tête et cou", "tête", "cou", "orl", "oreille", "nez", "gorge", "bouche", "dents", "dentaire", "maxillo"],
            "veines et artères": ["veines et artères", "veines", "artères", "vasculaire", "circulation", "sang", "vaisseaux", "cardio-vasculaire"],
            "orthopédie": ["orthopédie", "orthopédie", "orthopédique", "os", "articulation", "articulations", "squelette", "fracture", "prothèse", "prothèses"],
            "cardiologie": ["cardiologie", "cardiologie", "cardiaque", "cardiaques", "cœur", "coeur", "cardio", "circulation", "tension", "artérielle"],
            "urologie": ["urologie", "urologie", "urologique", "urine", "vessie", "rein", "reins", "prostate", "urinaire"],
            "psychiatrie": ["psychiatrie", "psychiatrie", "psychiatrique", "mental", "mentale", "psychologique", "dépression", "anxiété", "stress"],
            "cancer": ["cancer", "cancérologie", "cancerologie","cancero", "oncologie", "oncologique", "tumeur", "tumeurs", "métastase", "chimiothérapie"],
            "neurologie": ["neurologie", "neurologie", "neurologique", "neuro", "cerveau", "système nerveux", "parkinson", "alzheimer", "avc"],
            "diabète": ["diabète", "diabète", "diabétique", "sucre", "glycémie", "insuline", "endocrinologie"]
        }

general_cancer_terms = [
        "cancer",
        "cancers", 
        "le cancer",
        "les cancers",
        "du cancer",
        "des cancers",
        "pour cancer",
        "pour le cancer",
        "pour les cancers",
        "concernant le cancer",
        "concernant les cancers",
        "sur le cancer",
        "sur les cancers",
        "au niveau du cancer",
        "au niveau des cancers",
        "question cancer",
        "question cancers"
    ]

specialty_list = ['ablation varices',
 'accidents vasculaires cerebraux',
 'accouchements normaux',
 'accouchements risques',
 'adenome prostate',
 'amygdales et vegetations',
 'angioplastie coronaire',
 'appendicite',
 'arthrose main',
 'audition',
 'calculs urinaires',
 'cancer colon ou intestin',
 'cancer estomac ou oesophage',
 'cancer foie',
 'cancer orl',
 'cancer os enfant et adolescent',
 'cancer ovaire',
 'cancer pancreas',
 'cancer poumon',
 'cancer prostate',
 'cancer rein',
 'cancer sein',
 'cancer thyroide',
 'cancer uterus',
 'cancer vessie',
 'cancers peau',
 'cardiologie interventionnelle',
 'cataracte',
 'chirurgie arteres',
 'chirurgie canal carpien',
 'chirurgie cancers osseux adulte',
 'chirurgie cardiaque adulte',
 'chirurgie cardiaque enfant et adolescent',
 'chirurgie carotides',
 'chirurgie cheville',
 'chirurgie cornee',
 'chirurgie dentaire et orale adulte',
 'chirurgie dentaire et orale enfant et adolescent',
 'chirurgie dos adulte',
 'chirurgie dos enfant et adolescent',
 'chirurgie epaule',
 'chirurgie maxillo faciale',
 'chirurgie nez et sinus',
 'chirurgie obesite',
 'chirurgie pied',
 'chirurgie rectum',
 'chirurgie retine',
 'chirurgie sarcomes tissus mous',
 'chirurgie testicules adulte',
 'chirurgie testicules enfant et adolescent',
 'depression',
 'diabete adulte',
 'diabete enfant et adolescent',
 'endometriose',
 'epilepsie adulte',
 'epilepsie enfant et adolescent',
 'fibrome uterin',
 'glandes salivaires',
 'glaucome',
 'hernies abdomen',
 'hypertension arterielle',
 'infarctus myocarde',
 'insuffisance cardiaque',
 'leucemie adulte',
 'leucemie enfant et adolescent',
 'ligaments genou',
 'lymphome myelome adulte',
 'maladie parkinson',
 'maladies inflammatoires chroniques intestin mici',
 'medecine vasculaire',
 'pneumologie',
 'proctologie',
 'prothese genou',
 'prothese hanche',
 'rythmologie',
 'schizophrenie',
 'sclerose en plaques',
 'strabisme',
 'stress post traumatique',
 'tableau d honneur',
 'troubles bipolaires',
 'tumeurs cerveau adulte',
 'tumeurs cerveau enfant et adolescent',
 'urgences main',
 'vesicule biliaire']


generic_words = [
            "problème", "problèmes", "trouble", "troubles", "maladie", "maladies", "pathologie", "pathologies",
            "affection", "affections", "symptôme", "symptômes", "douleur", "douleurs", "soin", "soins",
            "prise en charge", "cas", "cas de", "cas du", "cas des", "cas d'", "question", "questions",
            "atteinte", "atteintes", "anomalie", "anomalies", "complication", "complications", "condition", "conditions",
            "situation", "situations", "traitement", "traitements", "gestion", "gestion de", "prévention", "prévention de",
            "risque", "risques", "manifestation", "manifestations", "syndrome", "syndromes", "infection", "infections",
            "inflammation", "inflammations", "consultation", "consultations", "examen", "examens", "intervention", "interventions",
            "chirurgie", "chirurgies", "suivi", "suivi de", "diagnostic", "diagnostics", "évaluation", "évaluations"
        ]